export const SEMANTIC_DRAFT_INSTRUCTIONS = `Extract the schedule from the complete source. Return JSON only in the supplied schema.

- Return every actionable task and calendar event exactly once. Include work, meetings, travel, meals, testing, preparation, and buffers when they consume time or affect the schedule. Ignore greetings, praise, and purely informational text.
- Use kind=event for a fixed activity anchored to a date/time. Use kind=task for work that can be placed before a deadline or inside a window. Use kind=milestone for an arrival-only checkpoint or passive prerequisite with no active work. Recurrence belongs in recurrence, not in kind.
- Resolve relative dates from Current local date. Dates are YYYY-MM-DD and local clocks are HH:mm. Never emit ISO timestamps.
- A bare weekday that is the current weekday means today unless wording such as “next” explicitly advances it.
- If an event has a clock but no date or resolvable day anywhere in the source, request date confirmation and set reviewRequired=true. Any reference date you use is provisional, not a stated date.
- occurrence.dateSourceText must quote the exact words establishing the event date (including a shared date elsewhere in the source). Use an empty string if no date is stated. Current local date is context for resolving relative words, never source evidence.
- A deadline at midnight means 23:59 at the end of the named day, never 00:00 at its beginning. In a range such as “1–3 PM”, apply PM to both clocks. “Morning at 9:30” means 09:30.
- occurrence is when a fixed event happens. Include startTime and endTime. When the end is unstated, make a reasonable duration estimate, set duration.explicit=false, and derive endTime from it.
- For a numeric event clock without AM/PM, such as "appointment at 5", retain a plausible startTime as a proposal, lower confidence, and request AM/PM confirmation with reviewRequired=true. Do not drop its date or start time merely because the meridiem is ambiguous.
- For vague event timing such as around lunch, keep the literal phrase in occurrence.period, omit exact clocks, and request confirmation instead of pretending noon was stated.
- deadline is when flexible work must be complete. Keep a hard deadline separate from a soft preferred work window.
- duration is the total active work for the whole responsibility, not the few seconds needed to click send, upload, or submit. Use the stated duration; otherwise estimate one and set explicit=false. Normalize words such as half an hour into numeric minutes. Set duration.approximate=true for rough durations such as about 35 minutes.
- Always fill planning. energyDemand is low, medium, or high. priority is low, medium, high, or urgent. category must be one of school, work, health, fitness, errand, personal, or other. estimatedMinutes must agree with duration. For a passive receipt or submission-only boundary with no active work, omit estimatedMinutes rather than returning zero.
- Put “no more than N minutes at once” in planning.maximumSessionMinutes and “across at least N days/sessions” in planning.sessionCount. Omit sessionCount unless the source requests at least two sessions or days.
- Put hard availability such as office hours in constraints.allowedWindows. Put preferences such as evening, before sunset, or an easier earlier completion in constraints.preferredWindows.
- Leave relationship-calculated clocks and proposed work slots to the app. Only put source-stated clocks in occurrence, deadline, or constraint boundaries, except for the explicitly review-flagged AM/PM event proposals described above and estimated event ends. Express relative timing through relations, even when you could calculate a clock yourself. Keep travel duration separate from an arrival buffer.
- Put recurring rules in recurrence, every one-time exception in conditionalRules, unavailable calendar blocks in blockedTimes, and prerequisites/order/buffers in relations. A recurring time range is an allowed window, not an exact recurrence time. Preserve commands such as “move earlier instead of skipping” as a conditional rule. A task-specific restriction such as “do not work on it tonight” belongs in that task's allowedWindows rather than becoming a global block. In a relation, fromId happens before or after toId as stated; put explicit buffer minutes in minimumGapMinutes. Connect every stated stage through the final deadline rather than stopping the dependency chain early.
- Apply corrections first. Keep only the newest active event or deadline and place superseded wording in ignoredStatements.
- For relations, supply your interpretation in reason and the relevant sourceText for reference. You own the meaning, implied references, duration conversion, and endpoint selection. Special timing goes directly to a calculator without source-quote matching or semantic validation, and its results require review. Main events are validated separately.
- Fill timing, fromBoundary, toBoundary, mode, approximate, and minimumGapMinutes. timing=ordering means general order; offset means a relative time; arrival_buffer means a zero-work checkpoint before an event; travel means a journey. Use these roles across all subjects, without scenario-specific assumptions.
- The calculator evaluates: from endpoint = to endpoint minus gap for before, or plus gap for after. A responsibility's end = its start + its own duration. minimumGapMinutes is ONLY the separation between the selected endpoints, not the responsibility's duration. Coincident endpoints have gap=0. Put work/travel length only in duration; put additional separation only in minimumGapMinutes. mode=exact gives an exact proposal; latest or earliest selects that boundary as the proposed placement. Mark estimates/preferences approximate. Keep main-event clocks in occurrence; omit calculated clocks and let the calculator do the arithmetic. References exist only during calculation: results are independent tasks, not linked groups.
- sourceText is an exact contiguous quote that includes the responsibility and nearby sentences containing its duration or conditions. Stable ids must be unique. Do not calculate character offsets unless certain.
- Lower confidence and list genuinely missing information when ambiguity changes a date, clock, or hard boundary. Do not mark a reasonable duration estimate as missing information.

Return responsibilities, relations, blockedTimes, globalInstructions, and ignoredStatements. Use empty arrays when none apply.`;
